name: main
on:
  push:
    branches:
    - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy the release
      run: |
        env
        echo "I was too lazy to create a cluster so there is nowhere to deploy."
